#!/usr/bin/env bash

echo ""
echo " __    __     _                   ___                          _             "
echo "/ / /\ \ \___| |__/\   /\/\/\    / _ \___ _ __   ___ _ __ __ _| |_ ___  _ __ "
echo "\ \/  \/ / _ \ '_ \ \ / /    \  / /_\/ _ \ '_ \ / _ \ '__/ _` | __/ _ \| '__|"
echo " \  /\  /  __/ |_) \ V / /\/\ \/ /_\\  __/ | | |  __/ | | (_| | || (_) | |   "
echo "  \/  \/ \___|_.__/ \_/\/    \/\____/\___|_| |_|\___|_|  \__,_|\__\___/|_|   "
echo ""
echo "                                                            by Cédric Dugat,"
echo "                                            Website: http://vmg.slynett.com."
echo ""
echo "Generator service to make your Vagrant + Puppet web Virtual Machines easily."
echo ""
echo "--> Installation in progress..."
echo ""
echo ""
