vagrantBox:               squeeze64
vagrantNFS:               true
vagrantMemory:            1024
vagrantCpu:               2
name:                     My pretty VM
ip:                       11.11.11.11
hostname:                 dev.local
timezone:                 Europe/Paris
php:                      true
phpPearComponents:        []
phpMyAdmin:               false
phpModules:               [ 'php5-mysql', 'php5-intl', 'php5-cli', 'php5-imagick', 'php5-gd', 'php5-xsl', 'php5-mcrypt', 'php5-curl', 'php5-xdebug', 'php5-imap' ]
phpXDebugMaxNestingLevel: 100
systemPackages:           [ 'build-essential', 'curl', 'git-core', 'vim' ]
apache:                   true
apachePort:               80
apacheRootDir:            /
apacheSSL:                false
nginx:                    false
varnish:                  false
mysql:                    true
mysqlRootPassword:        root
mailCatcher:              false
vimConfig:                false
composer:                 false
