label:                    No defined pre-configuration
vagrantBox:               squeeze64Puppet3
vagrantNFS:               true
vagrantMemory:            1024
vagrantCpu:               2
vagrantFinalLaunch:       true
name:                     My pretty VM
ip:                       11.11.11.11
hostname:                 dev.local
timezone:                 Europe/Paris
php:                      true
phpPearComponents:        []
phpMyAdmin:               false
phpModules:               [ 'mysql', 'intl', 'cli', 'imagick', 'gd', 'xsl', 'mcrypt', 'curl', 'xdebug', 'imap', 'apc' ]
phpXDebugMaxNestingLevel: 100
systemPackages:           [ 'build-essential', 'curl', 'git-core', 'vim' ]
apache:                   true
apachePort:               80
apacheRootDir:            /
apacheSSL:                false
nginx:                    false
nginxPort:                81
varnish:                  false
varnishPort:              82
mysql:                    true
mysqlRootPassword:        root
mailCatcher:              false
vimConfig:                false
composer:                 false
ohMyZsh:                  true
