configuration:
    name:       'My pretty VM'
    timezone:   'Europe/Paris'
    ip:         '11.11.11.11'
    hostname:   'dev.local'

db:
    mysqlRootPassword: root

phpModules: ['mysql', 'intl', 'xdebug', 'curl', 'sqlite', 'imagick', 'suhosin']
