name:               My pretty VM
ip:                 11.11.11.11
hostname:           dev.local
timezone:           Europe/Paris
php:                true
phpPear:            false
phpMyAdmin:         false
phpModules:         [ 'mysql', 'intl', 'curl', 'suhosin' ]
systemPackages:     [ 'git-core', 'vim' ]
apache:             true
apacheSSL:          false
nginx:              false
varnish:            false
mysql:              true
mysqlRootPassword:  root
vimConfig:          false
composer:           false
