vagrantBox:               squeeze64
vagrantNFS:               true
vagrantMemory:            1024
name:                     My pretty VM
ip:                       11.11.11.11
hostname:                 dev.local
timezone:                 Europe/Paris
php:                      true
phpPearComponents:        []
phpMyAdmin:               false
phpModules:               [ 'mysql', 'intl', 'cli', 'imagick', 'gd', 'xsl', 'mcrypt', 'curl', 'xdebug', 'imap' ]
phpXDebugMaxNestingLevel: 100
systemPackages:           [ 'build-essential', 'curl', 'git-core', 'vim' ]
apache:                   true
apachePort:               80
apacheRootDir:            /
apacheSSL:                false
nginx:                    false
varnish:                  false
mysql:                    true
mysqlRootPassword:        root
vimConfig:                false
composer:                 false
