mysql:
    path: modules/mysql
    url:  https://github.com/example42/puppet-mysql.git
apache:
    path: modules/apache
    url:  https://github.com/example42/puppet-apache.git
php:
    path: modules/php
    url:  https://github.com/example42/puppet-php.git
puppi:
    path: modules/puppi
    url:  https://github.com/example42/puppi.git
composer:
    path: modules/composer
    url:  https://github.com/willdurand/puppet-composer.git
