squeeze64:
    name: Debian 6.0.0 (Squeeze) - 64 bits
    url:  http://dl.dropbox.com/u/937870/VMs/squeeze64.box

precise64:
    name: Ubuntu 12.04 LTS (Precise) - 64 bits
    url:  http://files.vagrantup.com/precise64.box
